sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t base-repo -f Dockerfile.dev .

script: 
  - docker run -e CI=true base-repo npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "baserepo-docker"
  env: "Baserepodocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-764580058745"
  bucket_path: "baserepo-docker"
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  