sudo: required
language: generic
services:
  - docker

before_install:
  - cd web && docker build -t base_repo_web -f ./Dockerfile.dev . && cd ..

script: 
  - docker run -e CI=true base_repo_web npm run test 

after_success:
  - cd web && docker build -t $DOCKER_ID/base_repo_web . && cd ..
  - cd api && docker build -t $DOCKER_ID/base_repo_api . && cd ..
  - cd nginx && docker build -t $DOCKER_ID/base_repo_nginx . && cd ..
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push to Github CLI
  - docker push $DOCKER_ID/base_repo_web
  - docker push $DOCKER_ID/base_repo_api
  - docker push $DOCKER_ID/base_repo_nginx

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "baserepo-docker"
#   env: "Baserepodocker-env"
#   bucket_name: "elasticbeanstalk-us-east-1-764580058745"
#   bucket_path: "baserepo-docker"
#   on:
#     branch: main
#   access_key_id: $ACCESS_KEY_ID
#   secret_access_key: $SECRET_ACCESS_KEY
  